export const SCHEMES = [
  {id:"pm-kisan",title:"PM-KISAN Samman Nidhi",ministry:"Ministry of Agriculture",cat:"Agriculture",short:"Direct income support of ₹6,000/year to farmer families.",desc:"PM Kisan provides income support of ₹6,000 per year to small and marginal farmer families. Paid in three installments of ₹2,000 every 4 months directly into bank accounts.",benefits:["₹6,000/year direct bank transfer","No repayment required","3 installments of ₹2,000"],btype:"Financial",docs:["Aadhaar Card","Bank Passbook","Land Records"],deadline:"Ongoing",link:"https://pmkisan.gov.in",rules:{maxIncome:200000,farmerRequired:true,minAge:18},tags:["farmer","income","central"],pop:95,active:true},
  {id:"ayushman",title:"Ayushman Bharat – PMJAY",ministry:"Ministry of Health",cat:"Healthcare",short:"Health cover of ₹5 lakh/year for poor families.",desc:"Provides health insurance coverage up to ₹5 lakh per year per family for hospitalisation. Covers 1,500+ medical packages at empanelled hospitals across India.",benefits:["₹5 lakh/year health cover","Cashless treatment","Pre-existing conditions covered","1500+ hospitals"],btype:"Insurance",docs:["Aadhaar Card","Ration Card","Income Certificate"],deadline:"Ongoing",link:"https://pmjay.gov.in",rules:{maxIncome:100000},tags:["health","insurance","BPL"],pop:92,active:true},
  {id:"pm-awas",title:"PM Awas Yojana (Urban)",ministry:"Ministry of Housing",cat:"Housing",short:"Subsidised home loans for urban poor and middle income.",desc:"PMAY-U provides credit-linked subsidy on home loans for EWS, LIG and MIG groups for construction or purchase of a house in urban areas.",benefits:["Up to ₹2.67 lakh subsidy","Lower EMIs","Pucca house for all"],btype:"Subsidy",docs:["Aadhaar Card","Income Certificate","Bank Passbook"],deadline:"31 Dec 2024",link:"https://pmaymis.gov.in",rules:{maxIncome:1800000,minAge:18},tags:["housing","loan","urban"],pop:88,active:true},
  {id:"pm-mudra",title:"PM Mudra Yojana",ministry:"Ministry of Finance",cat:"Employment",short:"Collateral-free loans up to ₹10 lakh for small businesses.",desc:"MUDRA provides loans classified as Shishu (up to ₹50k), Kishore (₹50k–5L), and Tarun (₹5L–10L) for micro-enterprises. No collateral required.",benefits:["Loan up to ₹10 lakh","No collateral","Low interest rates"],btype:"Loan",docs:["Aadhaar Card","PAN Card","Business plan"],deadline:"Ongoing",link:"https://mudra.org.in",rules:{businessRequired:true,minAge:18},tags:["loan","business","entrepreneur"],pop:85,active:true},
  {id:"nsp",title:"National Scholarship Portal",ministry:"Ministry of Education",cat:"Education",short:"Scholarships for meritorious students from weaker sections.",desc:"NSP provides a single-window platform for students to apply for central and state scholarship schemes including pre-matric, post-matric and merit-cum-means scholarships.",benefits:["Monthly stipend","Book allowance","Academic support"],btype:"Scholarship",docs:["Aadhaar Card","Income Certificate","Caste Certificate","Bank Passbook"],deadline:"Oct 31, 2024",link:"https://scholarships.gov.in",rules:{studentRequired:true,maxIncome:200000,maxAge:30},tags:["scholarship","student","education"],pop:90,active:true},
  {id:"sukanya",title:"Sukanya Samriddhi Yojana",ministry:"Ministry of Finance",cat:"Women Empowerment",short:"Savings scheme for girl child education and marriage.",desc:"SSY offers high interest rates (8.2% p.a.) and tax benefits for the girl child. Min deposit ₹250, max ₹1.5 lakh per year. Account opens till girl is 10 years old.",benefits:["8.2% interest rate","Tax exemption under 80C","Maturity at age 21"],btype:"Financial",docs:["Aadhaar Card","Birth Certificate","Bank Passbook"],deadline:"Ongoing",link:"https://www.indiapost.gov.in",rules:{gender:"female",maxAge:10},tags:["girl child","savings","education"],pop:78,active:true},
  {id:"startup-india",title:"Startup India Initiative",ministry:"Ministry of Commerce",cat:"Startups / MSME",short:"Tax benefits, funding & mentorship for startups.",desc:"Startup India provides 3-year tax exemption, simplified compliance, IPR support and access to Fund of Funds. DPIIT recognition opens multiple government benefits.",benefits:["3 years income tax exemption","Fast-track IPR processing","₹10,000 Cr fund access","Mentorship"],btype:"Multiple",docs:["Incorporation Certificate","PAN Card","Business plan"],deadline:"Ongoing",link:"https://startupindia.gov.in",rules:{businessRequired:true,minAge:21},tags:["startup","business","innovation"],pop:82,active:true},
  {id:"disability-pension",title:"IGNDPS – Disability Pension",ministry:"Ministry of Rural Development",cat:"Disability Welfare",short:"Monthly pension for persons with severe disability.",desc:"Under NSAP, disabled persons aged 18–79 with 80%+ disability from BPL households receive a monthly pension of ₹300–₹500.",benefits:["₹300–₹500/month","Direct bank transfer"],btype:"Pension",docs:["Aadhaar Card","Disability Certificate","BPL Card","Bank Passbook"],deadline:"Ongoing",link:"https://nsap.nic.in",rules:{disabilityRequired:true,maxIncome:50000,minAge:18,maxAge:79},tags:["disability","pension","BPL"],pop:72,active:true},
  {id:"old-age-pension",title:"Indira Gandhi Old Age Pension",ministry:"Ministry of Rural Development",cat:"Pension",short:"Monthly pension for senior citizens below poverty line.",desc:"IGNOAPS provides ₹200/month for ages 60–79 and ₹500/month for ages 80+ to BPL households. State governments usually add a top-up amount.",benefits:["₹200–₹500/month","Direct bank transfer","State top-up additional"],btype:"Pension",docs:["Aadhaar Card","BPL Card","Age Proof","Bank Passbook"],deadline:"Ongoing",link:"https://nsap.nic.in",rules:{minAge:60,maxIncome:50000},tags:["senior","pension","BPL"],pop:80,active:true},
  {id:"skill-india",title:"PM Kaushal Vikas Yojana",ministry:"Ministry of Skill Development",cat:"Employment",short:"Free skill training and certification for youth.",desc:"PMKVY provides free short-term skill training under NSQF. Successful candidates receive certification and ₹8,000 reward. Job placement support provided.",benefits:["Free training","₹8,000 reward","Industry certificate","Placement support"],btype:"Training",docs:["Aadhaar Card","Educational certificates","Bank Passbook"],deadline:"Ongoing",link:"https://pmkvyofficial.org",rules:{minAge:15,maxAge:45,maxIncome:300000},tags:["skill","training","youth"],pop:87,active:true},
  {id:"nrega",title:"MGNREGS – Mahatma Gandhi NREGS",ministry:"Ministry of Rural Development",cat:"Employment",short:"100 days guaranteed wage employment for rural households.",desc:"MGNREGS guarantees 100 days of wage employment per year to rural households. Current wage: ₹220–₹362/day depending on state. Work provided within 5 km.",benefits:["100 days guaranteed work","₹220–₹362/day wages","Work within 5 km","Unemployment allowance"],btype:"Employment",docs:["Aadhaar Card","Job Card","Bank Passbook"],deadline:"Ongoing",link:"https://nrega.nic.in",rules:{minAge:18},tags:["employment","rural","wages"],pop:88,active:true},
  {id:"ujjwala",title:"PM Ujjwala Yojana",ministry:"Ministry of Petroleum",cat:"Welfare",short:"Free LPG connection to BPL women.",desc:"PMUY provides LPG connections free of cost to women from BPL households. Covers security deposit, regulator, hose, first refill and hotplate free of charge.",benefits:["Free LPG connection","First refill free","Safety equipment included"],btype:"Subsidy",docs:["Aadhaar Card","BPL / Ration Card","Bank Passbook"],deadline:"Ongoing",link:"https://pmuy.gov.in",rules:{gender:"female",maxIncome:100000},tags:["LPG","BPL","women","fuel"],pop:86,active:true},
  {id:"jeevan-jyoti",title:"PM Jeevan Jyoti Bima Yojana",ministry:"Ministry of Finance",cat:"Insurance",short:"₹2 lakh life insurance at just ₹436/year.",desc:"PMJJBY offers one-year renewable term life insurance of ₹2 lakh for death due to any cause. Premium ₹436/year, auto-debited from savings account every June.",benefits:["₹2 lakh life cover","₹436/year premium","Easy auto-debit enrollment"],btype:"Insurance",docs:["Aadhaar Card","Bank account"],deadline:"Ongoing",link:"https://jansuraksha.gov.in",rules:{minAge:18,maxAge:50},tags:["insurance","life","affordable"],pop:83,active:true},
  {id:"suraksha-bima",title:"PM Suraksha Bima Yojana",ministry:"Ministry of Finance",cat:"Insurance",short:"Accident insurance of ₹2 lakh at just ₹20/year.",desc:"PMSBY provides ₹2 lakh for accidental death and permanent total disability, ₹1 lakh for partial disability. Premium is just ₹20/year auto-debited from bank.",benefits:["₹2 lakh accident cover","₹20/year premium","Renewable annually"],btype:"Insurance",docs:["Aadhaar Card","Bank account"],deadline:"Ongoing",link:"https://jansuraksha.gov.in",rules:{minAge:18,maxAge:70},tags:["insurance","accident","affordable"],pop:79,active:true},
  {id:"atal-pension",title:"Atal Pension Yojana",ministry:"Ministry of Finance",cat:"Pension",short:"Guaranteed pension of ₹1,000–₹5,000/month after age 60.",desc:"APY guarantees fixed monthly pension between ₹1,000 and ₹5,000 after age 60 based on contribution. Joint funding by subscriber and Government of India.",benefits:["₹1,000–₹5,000/month pension","Govt co-contribution","Death benefit for family"],btype:"Pension",docs:["Aadhaar Card","Bank Passbook"],deadline:"Ongoing",link:"https://npscra.nsdl.co.in",rules:{minAge:18,maxAge:40},tags:["pension","retirement","savings"],pop:77,active:true},
  {id:"jan-dhan",title:"PM Jan Dhan Yojana",ministry:"Ministry of Finance",cat:"Financial Inclusion",short:"Zero-balance bank account with accident insurance & overdraft.",desc:"PMJDY ensures access to financial services. Includes RuPay debit card with ₹2 lakh accident insurance and ₹10,000 overdraft facility for active accounts.",benefits:["Zero-balance account","₹2 lakh accident insurance","₹10,000 overdraft","RuPay debit card"],btype:"Financial",docs:["Aadhaar Card","Address Proof"],deadline:"Ongoing",link:"https://pmjdy.gov.in",rules:{minAge:10},tags:["banking","financial inclusion"],pop:91,active:true},
  {id:"women-entrepreneur",title:"Mahila Udyam Nidhi Scheme",ministry:"Ministry of MSME",cat:"Women Empowerment",short:"Soft loans up to ₹10 lakh for women entrepreneurs.",desc:"Provides soft loans at concessional rates to women entrepreneurs for setting up small-scale enterprises. Repayment period up to 10 years with initial moratorium period.",benefits:["Loan up to ₹10 lakh","Concessional interest","10-year repayment"],btype:"Loan",docs:["Aadhaar Card","PAN Card","Business Plan","Income Certificate"],deadline:"Ongoing",link:"https://msme.gov.in",rules:{gender:"female",businessRequired:true,minAge:18},tags:["women","business","loan"],pop:70,active:true},
  {id:"pmegp",title:"PMEGP – Employment Generation",ministry:"Ministry of MSME",cat:"Employment",short:"Subsidy-linked loan for new micro-enterprises.",desc:"PMEGP provides 15–35% margin money subsidy for micro-enterprises. Project cost up to ₹25 lakh (manufacturing) and ₹10 lakh (service sector).",benefits:["15–35% subsidy","Loan up to ₹25 lakh","Training support"],btype:"Loan + Subsidy",docs:["Aadhaar Card","PAN Card","Educational certificates","Business plan"],deadline:"Ongoing",link:"https://kviconline.gov.in",rules:{minAge:18,businessRequired:true},tags:["employment","subsidy","business"],pop:75,active:true},
  {id:"stand-up-india",title:"Stand Up India",ministry:"Ministry of Finance",cat:"Startups / MSME",short:"Loans ₹10 lakh–₹1 crore for SC/ST/Women entrepreneurs.",desc:"Facilitates bank loans between ₹10 lakh and ₹1 crore to at least one SC/ST borrower and one woman per bank branch for greenfield enterprises.",benefits:["Loan ₹10 lakh–₹1 crore","7-year repayment","Working capital included"],btype:"Loan",docs:["Aadhaar Card","PAN Card","Business Plan","Caste Certificate"],deadline:"Ongoing",link:"https://standupmitra.in",rules:{businessRequired:true,minAge:18},tags:["SC/ST","women","business","loan"],pop:67,active:true},
  {id:"ddu-gky",title:"DDU-GKY Skill Training",ministry:"Ministry of Rural Development",cat:"Employment",short:"Free skill training with placement guarantee for rural youth.",desc:"DDU-GKY provides free skill training to rural poor youth aged 15–35. Training centres provide food, accommodation, and guaranteed placement with post-placement support.",benefits:["Free training","Food & accommodation","Job placement guarantee","Post-placement support"],btype:"Training",docs:["Aadhaar Card","Educational certificates","Domicile Certificate"],deadline:"Ongoing",link:"https://ddugky.gov.in",rules:{minAge:15,maxAge:35,maxIncome:100000},tags:["skill","rural","training","placement"],pop:69,active:true},
  {id:"pm-fasal-bima",title:"PM Fasal Bima Yojana",ministry:"Ministry of Agriculture",cat:"Agriculture",short:"Crop insurance at subsidised premiums for farmers.",desc:"PMFBY provides comprehensive risk coverage against crop loss from non-preventable natural risks. Premium: 2% (Kharif), 1.5% (Rabi). Rest paid by state and central government.",benefits:["Crop loss compensation","Low premium rates","Coverage for all crops"],btype:"Insurance",docs:["Aadhaar Card","Bank Passbook","Land Records","Sowing Certificate"],deadline:"Seasonal",link:"https://pmfby.gov.in",rules:{farmerRequired:true},tags:["crop insurance","farmer","agriculture"],pop:82,active:true},
  {id:"pm-poshan",title:"PM POSHAN – Mid Day Meal",ministry:"Ministry of Education",cat:"Education",short:"Free nutritious meal for school children daily.",desc:"PM POSHAN provides one hot cooked meal per day in all government and government-aided schools from Class 1 to 8. Covers 11.80 crore children nationally.",benefits:["Free nutritious meal daily","Improved attendance","Nutritional support"],btype:"In-kind",docs:["School enrollment certificate"],deadline:"Ongoing",link:"https://pmposhan.education.gov.in",rules:{studentRequired:true,maxAge:14},tags:["school","nutrition","children"],pop:84,active:true},
  {id:"bbbp",title:"Beti Bachao Beti Padhao",ministry:"Ministry of WCD",cat:"Women Empowerment",short:"Support girl child education and welfare.",desc:"BBBP aims to prevent gender-biased sex selective practices, ensure survival and protection of the girl child, and promote her education and participation in society.",benefits:["Financial support for education","Healthcare access","Awareness campaigns"],btype:"Multiple",docs:["Birth Certificate","Aadhaar Card"],deadline:"Ongoing",link:"https://wcd.nic.in",rules:{gender:"female",maxAge:18},tags:["girl child","education","women"],pop:73,active:true},
  {id:"svamitva",title:"PM SVAMITVA Scheme",ministry:"Ministry of Panchayati Raj",cat:"Housing",short:"Legal property rights card for rural households.",desc:"SVAMITVA provides property rights to rural household owners through drone survey. Provides 'Rights of Record' (property card) enabling bank loans and reducing disputes.",benefits:["Legal property document","Enables bank loans","Reduces land disputes"],btype:"Documentation",docs:["Aadhaar Card","Residence proof"],deadline:"Ongoing",link:"https://svamitva.nic.in",rules:{minAge:18},tags:["property","rural","rights"],pop:65,active:true},
  {id:"digital-saksharta",title:"PM Gramin Digital Saksharta",ministry:"Ministry of Electronics & IT",cat:"Digital Inclusion",short:"Free digital literacy training for rural households.",desc:"PMGDISHA aims to make 6 crore rural households digitally literate. Covers internet usage, digital payments, online government services and safety.",benefits:["Free digital training","NIELIT certificate","Digital payment skills"],btype:"Training",docs:["Aadhaar Card","Bank Passbook"],deadline:"Ongoing",link:"https://pmgdisha.in",rules:{maxIncome:200000},tags:["digital","rural","literacy"],pop:68,active:true},
  {id:"e-shram",title:"e-Shram Portal Registration",ministry:"Ministry of Labour",cat:"Employment",short:"National database and insurance for unorganised workers.",desc:"e-Shram provides UAN to unorganised sector workers with ₹2 lakh accident insurance under PMSBY. Links to direct benefit transfers and skill-employment support.",benefits:["Universal Account Number","₹2 lakh accident insurance","Direct benefit access","Skill support"],btype:"Multiple",docs:["Aadhaar Card","Bank Passbook"],deadline:"Ongoing",link:"https://eshram.gov.in",rules:{minAge:16,maxAge:59},tags:["unorganised","labour","insurance"],pop:78,active:true},
  {id:"solar-rooftop",title:"Solar Rooftop Subsidy",ministry:"Ministry of New & Renewable Energy",cat:"Digital Inclusion",short:"Subsidy for installing solar panels on rooftops.",desc:"Provides central financial assistance of 30–40% subsidy for rooftop solar installations up to 3 KW capacity, significantly reducing electricity bills.",benefits:["30–40% installation subsidy","Reduced electricity bills","Net metering support"],btype:"Subsidy",docs:["Aadhaar Card","Electricity bill","Property documents"],deadline:"Ongoing",link:"https://solarrooftop.gov.in",rules:{minAge:18},tags:["solar","energy","subsidy","green"],pop:71,active:true},
  {id:"rashtriya-vayoshri",title:"Rashtriya Vayoshri Yojana",ministry:"Ministry of Social Justice",cat:"Disability Welfare",short:"Free assistive devices for senior citizens with disabilities.",desc:"RVY provides free physical aids and assistive devices (walking sticks, wheelchairs, hearing aids, spectacles) to BPL senior citizens with age-related disabilities.",benefits:["Free assistive devices","On-site fitting camps","Quality certified devices"],btype:"In-kind",docs:["Aadhaar Card","Age Certificate","BPL Card","Disability Certificate"],deadline:"Ongoing",link:"https://socialjustice.nic.in",rules:{minAge:60,disabilityRequired:true,maxIncome:50000},tags:["senior","disability","assistive","BPL"],pop:62,active:true},
  {id:"pmrpy",title:"PM Rojgar Protsahan Yojana",ministry:"Ministry of Labour",cat:"Employment",short:"Government pays EPF contribution for new employees.",desc:"PMRPY incentivises employers to generate new employment by paying 12% Employer EPFO contribution for new employees earning up to ₹15,000/month for 3 years.",benefits:["12% EPF paid by government","Social security for new hires","3-year support"],btype:"Subsidy",docs:["EPFO registration","Business registration"],deadline:"Ongoing",link:"https://pmrpy.gov.in",rules:{businessRequired:true},tags:["employment","EPF","business"],pop:58,active:true},
  {id:"pm-scholarship-ksb",title:"PM Scholarship – Paramilitary Wards",ministry:"Ministry of Home Affairs",cat:"Education",short:"Scholarship for wards of ex/serving paramilitary personnel.",desc:"Provides ₹2,500/month (boys) and ₹3,000/month (girls) to wards of ex/serving paramilitary personnel for degree/diploma programmes.",benefits:["₹2,500–₹3,000/month","2–5 year duration","For degree/diploma"],btype:"Scholarship",docs:["Aadhaar","Marksheet","Service Certificate of parent","Bank Passbook"],deadline:"Aug 31, 2024",link:"https://ksb.gov.in",rules:{studentRequired:true,maxAge:25},tags:["scholarship","paramilitary","education"],pop:60,active:true}
];

export const CATS = [...new Set(SCHEMES.map(s => s.cat))];

export const STATES = ["Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Delhi","J&K"];

export const DOCS = ['Aadhaar Card','PAN Card','Bank Passbook','Income Certificate','Caste Certificate','Disability Certificate','Domicile Certificate','Ration Card','Land Records','Birth Certificate'];

export const CAT_EMOJI = {'Agriculture':'🌾','Healthcare':'🏥','Housing':'🏠','Employment':'💼','Education':'🎓','Women Empowerment':'👩','Insurance':'🛡️','Pension':'👴','Financial Inclusion':'🏦','Welfare':'🔥','Startups / MSME':'💡','Disability Welfare':'♿'};

export const CAT_COLORS = {'Agriculture':'#d1fae5','Healthcare':'#fee2e2','Housing':'#ede9fe','Employment':'#fef3c7','Education':'#dbeafe','Women Empowerment':'#fce7f3','Insurance':'#e0f2fe','Pension':'#fef9c3','Financial Inclusion':'#d1fae5','Welfare':'#fef3c7','Startups / MSME':'#f0fdf4','Disability Welfare':'#f0f9ff'};

export function checkEligibility(scheme, profile) {
  if (!profile || !profile.age) return {status:'unknown',score:0,matched:[],missing:[],missingDocs:[]};
  const r = scheme.rules;
  const matched=[], missing=[];
  let total=0, met=0;

  function check(cond, passLabel, failLabel) {
    if (cond === undefined) return;
    total++;
    if (cond) { met++; matched.push(passLabel); }
    else { missing.push(failLabel); }
  }

  check(r.minAge===undefined || profile.age>=r.minAge, `Age ≥ ${r.minAge}`, `Must be at least ${r.minAge} years old`);
  check(r.maxAge===undefined || profile.age<=r.maxAge, `Age ≤ ${r.maxAge}`, `Must be at most ${r.maxAge} years old`);
  check(r.gender===undefined || profile.gender===r.gender, `Gender: ${r.gender}`, `Must identify as ${r.gender}`);
  check(r.maxIncome===undefined || (profile.income||0)<=r.maxIncome, `Income ≤ ₹${(r.maxIncome||0).toLocaleString()}`, `Annual income must be below ₹${(r.maxIncome||0).toLocaleString()}`);
  check(r.farmerRequired===undefined || profile.isFarmer, 'Farmer status ✓', 'Must be a farmer');
  check(r.studentRequired===undefined || profile.isStudent, 'Student status ✓', 'Must be a student');
  check(r.disabilityRequired===undefined || profile.isDisabled, 'Disability status ✓', 'Must have disability certificate');
  check(r.businessRequired===undefined || profile.isBusiness, 'Business owner ✓', 'Must be a business owner');

  const reqDocs = scheme.docs || [];
  const userDocs = profile.documents || [];
  const missingDocs = reqDocs.filter(d => !userDocs.includes(d));

  const score = total===0 ? 100 : Math.round((met/total)*100);
  const status = missing.length===0 ? 'eligible' : score>=60 ? 'partial' : 'not-eligible';

  return {status, score, matched, missing, missingDocs};
}

export const DEMO_USERS = [
  {id:'1',name:'Demo User',email:'user@demo.com',password:'demo123',role:'user',profile:null,bookmarks:[]},
  {id:'2',name:'Admin User',email:'admin@demo.com',password:'admin123',role:'admin',profile:null,bookmarks:[]},
];
